//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.STOCK_FROM_MATERIAL {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="STOCK_FROM_MATERIAL.get_part_quantity_from_binSoap")]
    public interface get_part_quantity_from_binSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<string> HelloWorldAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Transit_stock_2002", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Transit_stock_2002(string stge_bin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Transit_stock_2002", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Transit_stock_2002Async(string stge_bin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/materials", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable materials(string stge_bin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/materials", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> materialsAsync(string stge_bin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/materials_2002_2005", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable materials_2002_2005(string stge_bin, string storage_location);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/materials_2002_2005", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> materials_2002_2005Async(string stge_bin, string storage_location);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PART_FROM_STORAGE_TYPE", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable PART_FROM_STORAGE_TYPE(string stge_type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PART_FROM_STORAGE_TYPE", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> PART_FROM_STORAGE_TYPEAsync(string stge_type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PART_FROM_STORAGE_TYPE_TO_EXCEL", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable PART_FROM_STORAGE_TYPE_TO_EXCEL(string stge_type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PART_FROM_STORAGE_TYPE_TO_EXCEL", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> PART_FROM_STORAGE_TYPE_TO_EXCELAsync(string stge_type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GET_PRODUCTION_QUANTITY_BY_ORDER", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GET_PRODUCTION_QUANTITY_BY_ORDER(string prod_order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GET_PRODUCTION_QUANTITY_BY_ORDER", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GET_PRODUCTION_QUANTITY_BY_ORDERAsync(string prod_order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GET_PRODUCTION_QUANTITY", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GET_PRODUCTION_QUANTITY(string dateFrom, string dateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GET_PRODUCTION_QUANTITY", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GET_PRODUCTION_QUANTITYAsync(string dateFrom, string dateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PART_FROM_STORAGE_TYPE_TO_EXCEL_00A", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable PART_FROM_STORAGE_TYPE_TO_EXCEL_00A(string stge_type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PART_FROM_STORAGE_TYPE_TO_EXCEL_00A", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> PART_FROM_STORAGE_TYPE_TO_EXCEL_00AAsync(string stge_type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PART_FROM_STORAGE_TYPE_TO_EXCEL_IM_MODULE", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable PART_FROM_STORAGE_TYPE_TO_EXCEL_IM_MODULE(string stge_loc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PART_FROM_STORAGE_TYPE_TO_EXCEL_IM_MODULE", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> PART_FROM_STORAGE_TYPE_TO_EXCEL_IM_MODULEAsync(string stge_loc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GET_MFRPN_TO_EXCEL", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GET_MFRPN_TO_EXCEL();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GET_MFRPN_TO_EXCEL", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GET_MFRPN_TO_EXCELAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PART_FROM_STORAGE_TYPE_TO_EXCEL_IM_MODULE_EMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable PART_FROM_STORAGE_TYPE_TO_EXCEL_IM_MODULE_EMS(string stge_loc, string material, string year);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PART_FROM_STORAGE_TYPE_TO_EXCEL_IM_MODULE_EMS", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> PART_FROM_STORAGE_TYPE_TO_EXCEL_IM_MODULE_EMSAsync(string stge_loc, string material, string year);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Submit_data_to_EMS_delivery", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Submit_data_to_EMS_delivery(string lot_num, string part_num, string reel_no, string qty, string box_number, string EMS);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Submit_data_to_EMS_delivery", ReplyAction="*")]
        System.Threading.Tasks.Task<string> Submit_data_to_EMS_deliveryAsync(string lot_num, string part_num, string reel_no, string qty, string box_number, string EMS);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckDuplicates", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int CheckDuplicates(string batch, string material, string reel_num, string ems_num);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckDuplicates", ReplyAction="*")]
        System.Threading.Tasks.Task<int> CheckDuplicatesAsync(string batch, string material, string reel_num, string ems_num);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PART_FROM_STORAGE_TYPE_TO_EXCEL_008", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable PART_FROM_STORAGE_TYPE_TO_EXCEL_008();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PART_FROM_STORAGE_TYPE_TO_EXCEL_008", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> PART_FROM_STORAGE_TYPE_TO_EXCEL_008Async();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Tracebility_PACKING_SYSTEM", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Tracebility_PACKING_SYSTEM(string productionOrder, string material, decimal quantity, string badge_number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Tracebility_PACKING_SYSTEM", ReplyAction="*")]
        System.Threading.Tasks.Task<string> Tracebility_PACKING_SYSTEMAsync(string productionOrder, string material, decimal quantity, string badge_number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PCB_SCAN_EMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string PCB_SCAN_EMS(string part_num, decimal qty, string batch, string ems_loc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PCB_SCAN_EMS", ReplyAction="*")]
        System.Threading.Tasks.Task<string> PCB_SCAN_EMSAsync(string part_num, decimal qty, string batch, string ems_loc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PART_FROM_STORAGE_TYPE_STORAGE_BIN", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable PART_FROM_STORAGE_TYPE_STORAGE_BIN(string stge_type, string stge_bin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PART_FROM_STORAGE_TYPE_STORAGE_BIN", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> PART_FROM_STORAGE_TYPE_STORAGE_BINAsync(string stge_type, string stge_bin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GET_STOCK_FROM_MATERIAL", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GET_STOCK_FROM_MATERIAL(string material);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GET_STOCK_FROM_MATERIAL", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GET_STOCK_FROM_MATERIALAsync(string material);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface get_part_quantity_from_binSoapChannel : WebApplication1.STOCK_FROM_MATERIAL.get_part_quantity_from_binSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class get_part_quantity_from_binSoapClient : System.ServiceModel.ClientBase<WebApplication1.STOCK_FROM_MATERIAL.get_part_quantity_from_binSoap>, WebApplication1.STOCK_FROM_MATERIAL.get_part_quantity_from_binSoap {
        
        public get_part_quantity_from_binSoapClient() {
        }
        
        public get_part_quantity_from_binSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public get_part_quantity_from_binSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public get_part_quantity_from_binSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public get_part_quantity_from_binSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync() {
            return base.Channel.HelloWorldAsync();
        }
        
        public System.Data.DataTable Transit_stock_2002(string stge_bin) {
            return base.Channel.Transit_stock_2002(stge_bin);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Transit_stock_2002Async(string stge_bin) {
            return base.Channel.Transit_stock_2002Async(stge_bin);
        }
        
        public System.Data.DataTable materials(string stge_bin) {
            return base.Channel.materials(stge_bin);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> materialsAsync(string stge_bin) {
            return base.Channel.materialsAsync(stge_bin);
        }
        
        public System.Data.DataTable materials_2002_2005(string stge_bin, string storage_location) {
            return base.Channel.materials_2002_2005(stge_bin, storage_location);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> materials_2002_2005Async(string stge_bin, string storage_location) {
            return base.Channel.materials_2002_2005Async(stge_bin, storage_location);
        }
        
        public System.Data.DataTable PART_FROM_STORAGE_TYPE(string stge_type) {
            return base.Channel.PART_FROM_STORAGE_TYPE(stge_type);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> PART_FROM_STORAGE_TYPEAsync(string stge_type) {
            return base.Channel.PART_FROM_STORAGE_TYPEAsync(stge_type);
        }
        
        public System.Data.DataTable PART_FROM_STORAGE_TYPE_TO_EXCEL(string stge_type) {
            return base.Channel.PART_FROM_STORAGE_TYPE_TO_EXCEL(stge_type);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> PART_FROM_STORAGE_TYPE_TO_EXCELAsync(string stge_type) {
            return base.Channel.PART_FROM_STORAGE_TYPE_TO_EXCELAsync(stge_type);
        }
        
        public System.Data.DataTable GET_PRODUCTION_QUANTITY_BY_ORDER(string prod_order) {
            return base.Channel.GET_PRODUCTION_QUANTITY_BY_ORDER(prod_order);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GET_PRODUCTION_QUANTITY_BY_ORDERAsync(string prod_order) {
            return base.Channel.GET_PRODUCTION_QUANTITY_BY_ORDERAsync(prod_order);
        }
        
        public System.Data.DataTable GET_PRODUCTION_QUANTITY(string dateFrom, string dateTo) {
            return base.Channel.GET_PRODUCTION_QUANTITY(dateFrom, dateTo);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GET_PRODUCTION_QUANTITYAsync(string dateFrom, string dateTo) {
            return base.Channel.GET_PRODUCTION_QUANTITYAsync(dateFrom, dateTo);
        }
        
        public System.Data.DataTable PART_FROM_STORAGE_TYPE_TO_EXCEL_00A(string stge_type) {
            return base.Channel.PART_FROM_STORAGE_TYPE_TO_EXCEL_00A(stge_type);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> PART_FROM_STORAGE_TYPE_TO_EXCEL_00AAsync(string stge_type) {
            return base.Channel.PART_FROM_STORAGE_TYPE_TO_EXCEL_00AAsync(stge_type);
        }
        
        public System.Data.DataTable PART_FROM_STORAGE_TYPE_TO_EXCEL_IM_MODULE(string stge_loc) {
            return base.Channel.PART_FROM_STORAGE_TYPE_TO_EXCEL_IM_MODULE(stge_loc);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> PART_FROM_STORAGE_TYPE_TO_EXCEL_IM_MODULEAsync(string stge_loc) {
            return base.Channel.PART_FROM_STORAGE_TYPE_TO_EXCEL_IM_MODULEAsync(stge_loc);
        }
        
        public System.Data.DataTable GET_MFRPN_TO_EXCEL() {
            return base.Channel.GET_MFRPN_TO_EXCEL();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GET_MFRPN_TO_EXCELAsync() {
            return base.Channel.GET_MFRPN_TO_EXCELAsync();
        }
        
        public System.Data.DataTable PART_FROM_STORAGE_TYPE_TO_EXCEL_IM_MODULE_EMS(string stge_loc, string material, string year) {
            return base.Channel.PART_FROM_STORAGE_TYPE_TO_EXCEL_IM_MODULE_EMS(stge_loc, material, year);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> PART_FROM_STORAGE_TYPE_TO_EXCEL_IM_MODULE_EMSAsync(string stge_loc, string material, string year) {
            return base.Channel.PART_FROM_STORAGE_TYPE_TO_EXCEL_IM_MODULE_EMSAsync(stge_loc, material, year);
        }
        
        public string Submit_data_to_EMS_delivery(string lot_num, string part_num, string reel_no, string qty, string box_number, string EMS) {
            return base.Channel.Submit_data_to_EMS_delivery(lot_num, part_num, reel_no, qty, box_number, EMS);
        }
        
        public System.Threading.Tasks.Task<string> Submit_data_to_EMS_deliveryAsync(string lot_num, string part_num, string reel_no, string qty, string box_number, string EMS) {
            return base.Channel.Submit_data_to_EMS_deliveryAsync(lot_num, part_num, reel_no, qty, box_number, EMS);
        }
        
        public int CheckDuplicates(string batch, string material, string reel_num, string ems_num) {
            return base.Channel.CheckDuplicates(batch, material, reel_num, ems_num);
        }
        
        public System.Threading.Tasks.Task<int> CheckDuplicatesAsync(string batch, string material, string reel_num, string ems_num) {
            return base.Channel.CheckDuplicatesAsync(batch, material, reel_num, ems_num);
        }
        
        public System.Data.DataTable PART_FROM_STORAGE_TYPE_TO_EXCEL_008() {
            return base.Channel.PART_FROM_STORAGE_TYPE_TO_EXCEL_008();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> PART_FROM_STORAGE_TYPE_TO_EXCEL_008Async() {
            return base.Channel.PART_FROM_STORAGE_TYPE_TO_EXCEL_008Async();
        }
        
        public string Tracebility_PACKING_SYSTEM(string productionOrder, string material, decimal quantity, string badge_number) {
            return base.Channel.Tracebility_PACKING_SYSTEM(productionOrder, material, quantity, badge_number);
        }
        
        public System.Threading.Tasks.Task<string> Tracebility_PACKING_SYSTEMAsync(string productionOrder, string material, decimal quantity, string badge_number) {
            return base.Channel.Tracebility_PACKING_SYSTEMAsync(productionOrder, material, quantity, badge_number);
        }
        
        public string PCB_SCAN_EMS(string part_num, decimal qty, string batch, string ems_loc) {
            return base.Channel.PCB_SCAN_EMS(part_num, qty, batch, ems_loc);
        }
        
        public System.Threading.Tasks.Task<string> PCB_SCAN_EMSAsync(string part_num, decimal qty, string batch, string ems_loc) {
            return base.Channel.PCB_SCAN_EMSAsync(part_num, qty, batch, ems_loc);
        }
        
        public System.Data.DataTable PART_FROM_STORAGE_TYPE_STORAGE_BIN(string stge_type, string stge_bin) {
            return base.Channel.PART_FROM_STORAGE_TYPE_STORAGE_BIN(stge_type, stge_bin);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> PART_FROM_STORAGE_TYPE_STORAGE_BINAsync(string stge_type, string stge_bin) {
            return base.Channel.PART_FROM_STORAGE_TYPE_STORAGE_BINAsync(stge_type, stge_bin);
        }
        
        public System.Data.DataTable GET_STOCK_FROM_MATERIAL(string material) {
            return base.Channel.GET_STOCK_FROM_MATERIAL(material);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GET_STOCK_FROM_MATERIALAsync(string material) {
            return base.Channel.GET_STOCK_FROM_MATERIALAsync(material);
        }
    }
}
